---
title: "Rotinas do Ambulatório de Uroginecologia"
subtitle: Serviço de Ginecologia do Hospital Universitário Pedro Ernesto - UERJ
author: Dr. Ricardo José de Souza, Ph.D. ^[Coordenador do ambulatório de uroginecologia no
  HUPE/UERJ e urologia feminina do Núcleo de Disfunção Miccional na Policlínica Piquet
  Carneiro/UERJ]
date: "versão 2023.2"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 5
    fig_caption: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
link-citations: yes
bibliography: references.bib
csl: elsevier-vancouver.csl
---

</div>

**Guia prático para Residentes, Pós-graduandos e Internos do HUPE**

</div>

## **Ambulatório do HUPE**

-   Salas 14 e 15 do prédio anexo ao HUPE

-   Atendimentos de mulheres com prolapso genital

-   Via SISREG ou SER (04 vagas)

-   Avaliação através de encaminhamento interno de mulheres com prolapso genital que necessitem de tratamento multidisciplinar

#### **Perfil da paciente**

-   Mulher com prolapso genital

-   Dor pélvica crônica associada a sintomas urinários ou prolapsos genitais

## **Ambulatório da Policlínica Piquet Carneiro**

-   Atendimento no Núcleo de Disfunção Miccional

-   Atendimentos de mulheres com queixas urinárias

-   Via SISREG ou SER

#### **Perfil da paciente**

-   Mulheres com incontinência urinária (sem prolapso genital)
-   Infecções urinárias de repetição
-   Fístulas urinárias
-   Divertículos de uretra
