---
title: "Linhas de Pesquisa da Uroginecologia - UERJ"
date: "versão 2023.2"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 5
    fig_caption: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
link-citations: yes
bibliography: references.bib
csl: elsevier-vancouver.csl
---


## Prolapsos genitais

Pesquisas realizadas no Hospital Universitário Pedro Ernesto

* Prevalência
* Associação com incontinência urinária
* Fatores de risco
* Comorbidades associadas
* Relação com qualidade de vida
* Relação com atividade sexual
* Opções terapêuticas
* Recidivas

## Incontinência urinária

Pesquisas realizadas na Policlínica Piquet Carneiro, no Núcleo de Disfunção Miccional

* Incontinência urinária e qualidade de vida
* Tipos de incontinência e prevalência
* Associação com atividade sexual
* Opções terapêuticas
* Falhas no tratamento e recidivas

## Síndrome da Bexiga Dolorosa

* Prevalência
* Características
* Diagnóstico
* Fenótipos
* Tratamento e falhas terapêuticas
* Opções terapêuticas
* Terapias promissoras